[tox]
minversion = 1.9
envlist =
	py{3.12,3.13}-django5.0
	py{3.12,3.13}-django5.1
	py{3.12,3.13}-djangomain
	ruff

[testenv]
setenv =
	PYTHONWARNINGS = always
	PYTHONDONTWRITEBYTECODE = 1
commands = pytest --cov=rgs_django_utils {posargs}
deps =
	django5.0: django~=5.0.0
	django5.1: django~=5.1.0
	djangomain: https://github.com/django/django/archive/main.tar.gz
	pytest
	pytest-django
	pytest-cov
	python-dotenv
	django-ninja~=1.4.0
	psycopg[binary]~=3.2
	cryptography>=42.0.0
	pyJWT>=2.8.0
	SqlAlchemy~=2.0
	GeoAlchemy2~=0.15
	xlsxwriter~=3.0

[testenv:ruff]
deps =
	ruff
commands =
	ruff check .
skip_install = true

[pytest]
# Default test paths to run, if no other paths are specified on the CLI.
testpaths = tests/
