# Generated by Django 5.2.1 on 2025-06-16 11:56

import django.db.models.deletion
import rgs_django_utils.database.dj_extended_models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionEnumTableType',
            fields=[
                ('id', rgs_django_utils.database.dj_extended_models.TextStringField(primary_key=True, serialize=False, verbose_name='code')),
                ('name', rgs_django_utils.database.dj_extended_models.TextStringField(verbose_name='name')),
            ],
            options={
                'verbose_name': 'tabeltype',
                'verbose_name_plural': 'tabeltypes',
                'db_table': 'descr_enum_table_type',
            },
        ),
        migrations.CreateModel(
            name='DescriptionTableSection',
            fields=[
                ('code', rgs_django_utils.database.dj_extended_models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', rgs_django_utils.database.dj_extended_models.TextField(blank=True, null=True, verbose_name='naam')),
                ('order', rgs_django_utils.database.dj_extended_models.IntegerField(db_default=-1, verbose_name='volgorde')),
                ('description', rgs_django_utils.database.dj_extended_models.TextField(blank=True, null=True, verbose_name='omschrijving')),
            ],
            options={
                'verbose_name': 'sectie',
                'verbose_name_plural': 'secties',
                'db_table': 'descr_table_section',
            },
        ),
        migrations.CreateModel(
            name='EnumAuthMethod',
            fields=[
                ('id', rgs_django_utils.database.dj_extended_models.TextStringField(primary_key=True, serialize=False, verbose_name='code')),
                ('name', rgs_django_utils.database.dj_extended_models.TextStringField(verbose_name='name')),
            ],
            options={
                'verbose_name': 'authenticatie methode',
                'verbose_name_plural': 'authenticatie methoden',
                'db_table': 'enum_auth_method',
            },
        ),
        migrations.CreateModel(
            name='EnumDataType',
            fields=[
                ('id', rgs_django_utils.database.dj_extended_models.TextStringField(primary_key=True, serialize=False, verbose_name='code')),
                ('name', rgs_django_utils.database.dj_extended_models.TextStringField(verbose_name='name')),
            ],
            options={
                'verbose_name': 'Datatype',
                'verbose_name_plural': 'Datatypes',
                'db_table': 'enum_data_type',
            },
        ),
        migrations.CreateModel(
            name='EnumFilePurpose',
            fields=[
                ('id', rgs_django_utils.database.dj_extended_models.TextStringField(primary_key=True, serialize=False, verbose_name='code')),
                ('name', rgs_django_utils.database.dj_extended_models.TextStringField(verbose_name='name')),
            ],
            options={
                'verbose_name': 'bestandsdoel',
                'verbose_name_plural': 'bestandsdoelen',
                'db_table': 'enum_file_purpose',
            },
        ),
        migrations.CreateModel(
            name='EnumImportMode',
            fields=[
                ('id', rgs_django_utils.database.dj_extended_models.TextStringField(primary_key=True, serialize=False, verbose_name='code')),
                ('name', rgs_django_utils.database.dj_extended_models.TextStringField(verbose_name='name')),
            ],
            options={
                'verbose_name': 'import mode',
                'verbose_name_plural': 'import modes',
                'db_table': 'enum_import_mode',
            },
        ),
        migrations.CreateModel(
            name='EnumMessageCode',
            fields=[
                ('id', rgs_django_utils.database.dj_extended_models.TextStringField(primary_key=True, serialize=False, verbose_name='code')),
                ('name', rgs_django_utils.database.dj_extended_models.TextStringField(verbose_name='name')),
            ],
            options={
                'verbose_name': 'Meldingscode',
                'verbose_name_plural': 'Meldingscodes',
                'db_table': 'enum_message_code',
            },
        ),
        migrations.CreateModel(
            name='EnumRole',
            fields=[
                ('id', rgs_django_utils.database.dj_extended_models.TextStringField(primary_key=True, serialize=False, verbose_name='code')),
                ('name', rgs_django_utils.database.dj_extended_models.TextStringField(verbose_name='name')),
            ],
            options={
                'verbose_name': 'Gebruikersrol',
                'verbose_name_plural': 'Gebruikersrollen',
                'db_table': 'enum_role',
            },
        ),
        migrations.CreateModel(
            name='EnumSourceType',
            fields=[
                ('id', rgs_django_utils.database.dj_extended_models.TextStringField(primary_key=True, serialize=False, verbose_name='code')),
                ('name', rgs_django_utils.database.dj_extended_models.TextStringField(verbose_name='name')),
            ],
            options={
                'verbose_name': 'Brontype',
                'verbose_name_plural': 'Brontypes',
                'db_table': 'enum_source_type',
            },
        ),
        migrations.CreateModel(
            name='EnumTaskStatus',
            fields=[
                ('id', rgs_django_utils.database.dj_extended_models.TextStringField(primary_key=True, serialize=False, verbose_name='code')),
                ('name', rgs_django_utils.database.dj_extended_models.TextStringField(verbose_name='name')),
            ],
            options={
                'verbose_name': 'Taakstatus',
                'verbose_name_plural': 'Taakstatussen',
                'db_table': 'enum_task_status',
            },
        ),
        migrations.CreateModel(
            name='EnumWorkflowStep',
            fields=[
                ('id', rgs_django_utils.database.dj_extended_models.TextStringField(primary_key=True, serialize=False, verbose_name='code')),
                ('name', rgs_django_utils.database.dj_extended_models.TextStringField(verbose_name='name')),
            ],
            options={
                'verbose_name': 'Workflow stap',
                'verbose_name_plural': 'workflow stappen',
                'db_table': 'enum_workflow_step',
            },
        ),
        migrations.CreateModel(
            name='EnumWorkflowType',
            fields=[
                ('id', rgs_django_utils.database.dj_extended_models.TextStringField(primary_key=True, serialize=False, verbose_name='code')),
                ('name', rgs_django_utils.database.dj_extended_models.TextStringField(verbose_name='name')),
            ],
            options={
                'verbose_name': 'workflow type',
                'verbose_name_plural': 'workflow types',
                'db_table': 'enum_workflow_type',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_last_modified', rgs_django_utils.database.dj_extended_models.DateTimeField(auto_now=True, verbose_name='laatst aangepast in central database')),
                ('last_modified_at', rgs_django_utils.database.dj_extended_models.DateTimeField(auto_now=True, verbose_name='laatst aangepast op')),
                ('created_at', rgs_django_utils.database.dj_extended_models.DateTimeField(db_default=models.Func(function='now'), verbose_name='aangemaakt op')),
                ('log_level', rgs_django_utils.database.dj_extended_models.IntegerField(default=25)),
                ('started', rgs_django_utils.database.dj_extended_models.DateTimeField(blank=True, null=True)),
                ('finished', rgs_django_utils.database.dj_extended_models.DateTimeField(blank=True, null=True)),
                ('max_memory_usage', rgs_django_utils.database.dj_extended_models.IntegerField(blank=True, null=True)),
                ('running_on', rgs_django_utils.database.dj_extended_models.TextField(blank=True, null=True)),
                ('config', rgs_django_utils.database.dj_extended_models.JSONField(blank=True, null=True, verbose_name='configuratie')),
                ('output', rgs_django_utils.database.dj_extended_models.JSONField(blank=True, null=True, verbose_name='output')),
                ('created_by', rgs_django_utils.database.dj_extended_models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='aangemaakt door')),
                ('last_modified_by', rgs_django_utils.database.dj_extended_models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='last_modified_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='laatst aangepast door')),
                ('status', rgs_django_utils.database.dj_extended_models.ForeignKey(default='not_started', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rgs_django_utils.enumtaskstatus', verbose_name='status')),
                ('step', rgs_django_utils.database.dj_extended_models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rgs_django_utils.enumworkflowstep', verbose_name='stap')),
            ],
            options={
                'verbose_name': 'taak',
                'verbose_name_plural': 'taak',
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='DescriptionTable',
            fields=[
                ('id', rgs_django_utils.database.dj_extended_models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='database tabel')),
                ('order', rgs_django_utils.database.dj_extended_models.IntegerField(db_default=-1)),
                ('model', rgs_django_utils.database.dj_extended_models.TextField(blank=True, null=True, verbose_name='model')),
                ('name', rgs_django_utils.database.dj_extended_models.TextField(verbose_name='naam')),
                ('name_plural', rgs_django_utils.database.dj_extended_models.TextField(blank=True, null=True, verbose_name='naam meervoud')),
                ('description', rgs_django_utils.database.dj_extended_models.TextField(blank=True, null=True, verbose_name='description')),
                ('modules', rgs_django_utils.database.dj_extended_models.TextField(default='*')),
                ('with_history', rgs_django_utils.database.dj_extended_models.BooleanField(db_default=False, verbose_name='met historie')),
                ('table_type', rgs_django_utils.database.dj_extended_models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rgs_django_utils.descriptionenumtabletype', verbose_name='tabeltype')),
                ('section', rgs_django_utils.database.dj_extended_models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='rgs_django_utils.descriptiontablesection', verbose_name='sectie')),
            ],
            options={
                'verbose_name': 'tabelbeschrijving',
                'verbose_name_plural': 'tabelbeschrijvingen',
                'db_table': 'descr_table',
            },
        ),
        migrations.CreateModel(
            name='DescriptionFieldSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', rgs_django_utils.database.dj_extended_models.CharField(max_length=50)),
                ('name', rgs_django_utils.database.dj_extended_models.TextField(blank=True, null=True, verbose_name='naam')),
                ('order', rgs_django_utils.database.dj_extended_models.IntegerField(db_default=-1, verbose_name='volgorde')),
                ('description', rgs_django_utils.database.dj_extended_models.TextField(blank=True, null=True, verbose_name='omschrijving')),
                ('table', rgs_django_utils.database.dj_extended_models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_sections', to='rgs_django_utils.descriptiontable', verbose_name='tabel')),
            ],
            options={
                'verbose_name': 'veldsectie',
                'verbose_name_plural': 'veldsecties',
                'db_table': 'descr_field_section',
            },
        ),
        migrations.CreateModel(
            name='DescriptionCalculation',
            fields=[
                ('id', rgs_django_utils.database.dj_extended_models.IntegerField(primary_key=True, serialize=False)),
                ('name', rgs_django_utils.database.dj_extended_models.TextField()),
                ('description', rgs_django_utils.database.dj_extended_models.TextField(verbose_name='description')),
                ('table', rgs_django_utils.database.dj_extended_models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='rgs_django_utils.descriptiontable', verbose_name='tabel')),
            ],
            options={
                'verbose_name': 'berekening',
                'verbose_name_plural': 'berekeningen',
                'db_table': 'descr_calculation',
            },
        ),
        migrations.CreateModel(
            name='EnumAuthMethodExtended',
            fields=[
                ('name', rgs_django_utils.database.dj_extended_models.TextStringField(verbose_name='name')),
                ('order', rgs_django_utils.database.dj_extended_models.IntegerField(verbose_name='volgorde')),
                ('available', rgs_django_utils.database.dj_extended_models.BooleanField(default=False, verbose_name='beschikbaar')),
                ('extra_costs', rgs_django_utils.database.dj_extended_models.BooleanField(verbose_name='extra kosten')),
                ('am_note', rgs_django_utils.database.dj_extended_models.TextField(blank=True, null=True, verbose_name='notities applicatie/ontwikkelaars')),
                ('id', rgs_django_utils.database.dj_extended_models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extended', serialize=False, to='rgs_django_utils.enumauthmethod')),
            ],
            options={
                'verbose_name': 'authenticatie methode',
                'verbose_name_plural': 'authenticatie methoden',
                'db_table': 'enum_auth_method_ext',
            },
        ),
        migrations.CreateModel(
            name='EnumDataTypeExtended',
            fields=[
                ('name', rgs_django_utils.database.dj_extended_models.TextStringField(verbose_name='name')),
                ('order', rgs_django_utils.database.dj_extended_models.IntegerField(default=0, verbose_name='volgorde')),
                ('poid_nr', rgs_django_utils.database.dj_extended_models.IntegerField(default=0, verbose_name='POID nummer')),
                ('id', rgs_django_utils.database.dj_extended_models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extended', serialize=False, to='rgs_django_utils.enumdatatype')),
            ],
            options={
                'verbose_name': 'Datatype',
                'verbose_name_plural': 'Datatypes',
                'db_table': 'enum_data_type_ext',
            },
        ),
        migrations.CreateModel(
            name='DescriptionField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', rgs_django_utils.database.dj_extended_models.IntegerField(db_default=-1, verbose_name='volgorde')),
                ('column_name', rgs_django_utils.database.dj_extended_models.TextField(verbose_name='kolomnaam')),
                ('verbose_name', rgs_django_utils.database.dj_extended_models.TextField(verbose_name='naam')),
                ('dbf_name', rgs_django_utils.database.dj_extended_models.CharField(blank=True, max_length=10, null=True, verbose_name='dbf naam')),
                ('field_type', rgs_django_utils.database.dj_extended_models.TextField(verbose_name='veldtype')),
                ('max_length', rgs_django_utils.database.dj_extended_models.IntegerField(blank=True, null=True, verbose_name='maximale lengte')),
                ('nullable', rgs_django_utils.database.dj_extended_models.BooleanField(verbose_name='nullable')),
                ('precision', rgs_django_utils.database.dj_extended_models.IntegerField(blank=True, null=True, verbose_name='aantal decimalen')),
                ('is_relation', rgs_django_utils.database.dj_extended_models.BooleanField(db_default=False, verbose_name='is relatie')),
                ('modules', rgs_django_utils.database.dj_extended_models.TextField(default='*')),
                ('doc_unit', rgs_django_utils.database.dj_extended_models.TextField(blank=True, null=True, verbose_name='eenheid')),
                ('doc_short', rgs_django_utils.database.dj_extended_models.TextField(blank=True, null=True, verbose_name='omschrijving kort')),
                ('doc_full', rgs_django_utils.database.dj_extended_models.TextField(blank=True, null=True, verbose_name='omschrijving volledig')),
                ('doc_constraint', rgs_django_utils.database.dj_extended_models.TextField(blank=True, null=True, verbose_name='omschrijving voorwaarde')),
                ('doc_development', rgs_django_utils.database.dj_extended_models.TextField(blank=True, null=True, verbose_name='omschrijving voor ontwikkelaars')),
                ('export', rgs_django_utils.database.dj_extended_models.BooleanField(db_default=True, verbose_name='export')),
                ('default_value', rgs_django_utils.database.dj_extended_models.TextField(blank=True, null=True, verbose_name='default waarde of functie')),
                ('with_history', rgs_django_utils.database.dj_extended_models.BooleanField(db_default=False, verbose_name='gebruikt in historie trigger')),
                ('calc_by', rgs_django_utils.database.dj_extended_models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='rgs_django_utils.descriptioncalculation', verbose_name='berekening')),
                ('field_section', rgs_django_utils.database.dj_extended_models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='rgs_django_utils.descriptionfieldsection', verbose_name='veldsectie')),
                ('relation_table', rgs_django_utils.database.dj_extended_models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relation_fields', to='rgs_django_utils.descriptiontable', verbose_name='relatie tabel')),
                ('table', rgs_django_utils.database.dj_extended_models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='rgs_django_utils.descriptiontable', verbose_name='tabel')),
                ('import_mode', rgs_django_utils.database.dj_extended_models.ForeignKey(default='all', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rgs_django_utils.enumimportmode', verbose_name='import mode')),
            ],
            options={
                'verbose_name': 'veld',
                'verbose_name_plural': 'velden',
                'db_table': 'descr_field',
            },
        ),
        migrations.CreateModel(
            name='EnumMessageCodeExtended',
            fields=[
                ('name', rgs_django_utils.database.dj_extended_models.TextStringField(verbose_name='name')),
                ('template', rgs_django_utils.database.dj_extended_models.TextField(blank=True, null=True, verbose_name='template')),
                ('template_fields', rgs_django_utils.database.dj_extended_models.ArrayField(base_field=rgs_django_utils.database.dj_extended_models.TextField(), size=None)),
                ('id', rgs_django_utils.database.dj_extended_models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extended', serialize=False, to='rgs_django_utils.enummessagecode')),
            ],
            options={
                'verbose_name': 'Meldingscode',
                'verbose_name_plural': 'Meldingscodes',
                'db_table': 'enum_message_code_ext',
            },
        ),
        migrations.CreateModel(
            name='EnumRoleExtended',
            fields=[
                ('name', rgs_django_utils.database.dj_extended_models.TextStringField(verbose_name='name')),
                ('for_staff', rgs_django_utils.database.dj_extended_models.BooleanField(default=False, verbose_name='Voor superuser')),
                ('for_org', rgs_django_utils.database.dj_extended_models.BooleanField(default=False, verbose_name='Voor organisatie')),
                ('for_project', rgs_django_utils.database.dj_extended_models.BooleanField(default=False, verbose_name='Voor project')),
                ('order', rgs_django_utils.database.dj_extended_models.IntegerField(default=0, verbose_name='volgorde')),
                ('description', rgs_django_utils.database.dj_extended_models.TextField(verbose_name='omschrijving')),
                ('id', rgs_django_utils.database.dj_extended_models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extended', serialize=False, to='rgs_django_utils.enumrole')),
            ],
            options={
                'verbose_name': 'Gebruikersrol',
                'verbose_name_plural': 'Gebruikersrollen',
                'db_table': 'enum_role_ext',
            },
        ),
        migrations.CreateModel(
            name='EnumSourceTypeExtended',
            fields=[
                ('name', rgs_django_utils.database.dj_extended_models.TextStringField(verbose_name='name')),
                ('order', rgs_django_utils.database.dj_extended_models.IntegerField(default=0, verbose_name='volgorde')),
                ('for_import', rgs_django_utils.database.dj_extended_models.BooleanField(default=False, verbose_name='Voor import')),
                ('for_export', rgs_django_utils.database.dj_extended_models.BooleanField(default=False, verbose_name='Voor export')),
                ('id', rgs_django_utils.database.dj_extended_models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extended', serialize=False, to='rgs_django_utils.enumsourcetype')),
            ],
            options={
                'verbose_name': 'Brontype',
                'verbose_name_plural': 'Brontypes',
                'db_table': 'enum_source_type_ext',
            },
        ),
        migrations.CreateModel(
            name='EnumTaskStatusExtended',
            fields=[
                ('name', rgs_django_utils.database.dj_extended_models.TextStringField(verbose_name='name')),
                ('order', rgs_django_utils.database.dj_extended_models.IntegerField(default=0, verbose_name='volgorde')),
                ('id', rgs_django_utils.database.dj_extended_models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extended', serialize=False, to='rgs_django_utils.enumtaskstatus')),
            ],
            options={
                'verbose_name': 'Taakstatus',
                'verbose_name_plural': 'Taakstatussen',
                'db_table': 'enum_task_status_ext',
            },
        ),
        migrations.CreateModel(
            name='EnumWorkflowStepExtended',
            fields=[
                ('name', rgs_django_utils.database.dj_extended_models.TextStringField(verbose_name='name')),
                ('order', rgs_django_utils.database.dj_extended_models.IntegerField(default=0, verbose_name='volgorde')),
                ('action', rgs_django_utils.database.dj_extended_models.TextField(default='', verbose_name='actie')),
                ('for_import', rgs_django_utils.database.dj_extended_models.BooleanField(default=False, verbose_name='Voor import')),
                ('for_export', rgs_django_utils.database.dj_extended_models.BooleanField(default=False, verbose_name='Voor export')),
                ('for_processing', rgs_django_utils.database.dj_extended_models.BooleanField(default=False, verbose_name='Voor processing')),
                ('id', rgs_django_utils.database.dj_extended_models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extended', serialize=False, to='rgs_django_utils.enumworkflowstep')),
            ],
            options={
                'verbose_name': 'Workflow stap',
                'verbose_name_plural': 'workflow stappen',
                'db_table': 'enum_workflow_step_ext',
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('db_last_modified', rgs_django_utils.database.dj_extended_models.DateTimeField(auto_now=True, verbose_name='laatst aangepast in central database')),
                ('last_modified_at', rgs_django_utils.database.dj_extended_models.DateTimeField(auto_now=True, verbose_name='laatst aangepast op')),
                ('created_at', rgs_django_utils.database.dj_extended_models.DateTimeField(db_default=models.Func(function='now'), verbose_name='aangemaakt op')),
                ('id', rgs_django_utils.database.dj_extended_models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', rgs_django_utils.database.dj_extended_models.UUIDField(db_default=models.Func(function='uuid7'))),
                ('filename', rgs_django_utils.database.dj_extended_models.TextField(blank=True, null=True, verbose_name='bestandsnaam')),
                ('remarks', rgs_django_utils.database.dj_extended_models.TextField(blank=True, null=True, verbose_name='opmerkingen')),
                ('file', rgs_django_utils.database.dj_extended_models.FileField(blank=True, null=True, upload_to='')),
                ('created_by', rgs_django_utils.database.dj_extended_models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='aangemaakt door')),
                ('file_purpose', rgs_django_utils.database.dj_extended_models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rgs_django_utils.enumfilepurpose', verbose_name='bestandsdoel')),
                ('last_modified_by', rgs_django_utils.database.dj_extended_models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='last_modified_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='laatst aangepast door')),
                ('project', rgs_django_utils.database.dj_extended_models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'project bestand',
                'verbose_name_plural': 'project bestanden',
                'db_table': 'project_file',
            },
        ),
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('task', rgs_django_utils.database.dj_extended_models.OneToOneField(db_column='id', editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='progress', serialize=False, to='rgs_django_utils.task')),
                ('description', rgs_django_utils.database.dj_extended_models.TextField(default='Nog niet gestart...', verbose_name='beschrijving')),
                ('progress', rgs_django_utils.database.dj_extended_models.IntegerField(default=0, verbose_name='voortgang')),
                ('db_last_modified', rgs_django_utils.database.dj_extended_models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'taak voortgang',
                'verbose_name_plural': 'taak voortgangen',
                'db_table': 'task_progress',
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', rgs_django_utils.database.dj_extended_models.BigAutoField(primary_key=True, serialize=False)),
                ('dt', rgs_django_utils.database.dj_extended_models.DateTimeField(auto_now_add=True)),
                ('level', rgs_django_utils.database.dj_extended_models.IntegerField(default=20)),
                ('message', rgs_django_utils.database.dj_extended_models.TextField(verbose_name='bericht')),
                ('name', rgs_django_utils.database.dj_extended_models.TextStringField(verbose_name='naam')),
                ('obj', rgs_django_utils.database.dj_extended_models.TextStringField(blank=True, null=True, verbose_name='object')),
                ('extra', rgs_django_utils.database.dj_extended_models.JSONField(blank=True, null=True, verbose_name='extra')),
                ('task', rgs_django_utils.database.dj_extended_models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='rgs_django_utils.task')),
            ],
            options={
                'verbose_name': 'taak log',
                'verbose_name_plural': 'taak logs',
                'db_table': 'task_log',
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_last_modified', rgs_django_utils.database.dj_extended_models.DateTimeField(auto_now=True, verbose_name='laatst aangepast in central database')),
                ('last_modified_at', rgs_django_utils.database.dj_extended_models.DateTimeField(auto_now=True, verbose_name='laatst aangepast op')),
                ('created_at', rgs_django_utils.database.dj_extended_models.DateTimeField(db_default=models.Func(function='now'), verbose_name='aangemaakt op')),
                ('uuid', rgs_django_utils.database.dj_extended_models.UUIDField(db_default=models.Func(function='uuid7'), editable=False)),
                ('name', rgs_django_utils.database.dj_extended_models.TextField(blank=True, null=True, verbose_name='naam')),
                ('remarks', rgs_django_utils.database.dj_extended_models.TextField(blank=True, null=True, verbose_name='opmerkingen')),
                ('locked', rgs_django_utils.database.dj_extended_models.BooleanField(default=False)),
                ('db_execution_dt', rgs_django_utils.database.dj_extended_models.DateTimeField(blank=True, null=True, verbose_name='datum verwerking in database')),
                ('counts', rgs_django_utils.database.dj_extended_models.JSONField(blank=True, null=True, verbose_name='aantallen')),
                ('summary', rgs_django_utils.database.dj_extended_models.JSONField(blank=True, null=True, verbose_name='samenvatting')),
                ('active_step', rgs_django_utils.database.dj_extended_models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rgs_django_utils.task', verbose_name='actieve stap')),
                ('created_by', rgs_django_utils.database.dj_extended_models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='aangemaakt door')),
                ('last_modified_by', rgs_django_utils.database.dj_extended_models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='last_modified_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='laatst aangepast door')),
                ('proj_file', rgs_django_utils.database.dj_extended_models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rgs_django_utils.projectfile')),
                ('project', rgs_django_utils.database.dj_extended_models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.project')),
                ('selection', rgs_django_utils.database.dj_extended_models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.selection')),
            ],
            options={
                'verbose_name': 'workflow',
                'verbose_name_plural': 'workflows',
                'db_table': 'workflow',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='workflow',
            field=rgs_django_utils.database.dj_extended_models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='rgs_django_utils.workflow'),
        ),
        migrations.CreateModel(
            name='WorkflowDataLog',
            fields=[
                ('id', rgs_django_utils.database.dj_extended_models.BigAutoField(primary_key=True, serialize=False)),
                ('dt', rgs_django_utils.database.dj_extended_models.DateTimeField(auto_now_add=True)),
                ('level', rgs_django_utils.database.dj_extended_models.IntegerField(default=20)),
                ('obj_name', rgs_django_utils.database.dj_extended_models.TextField(blank=True, null=True, verbose_name='object')),
                ('record_id', rgs_django_utils.database.dj_extended_models.JSONField(blank=True, null=True, verbose_name='record id')),
                ('fields', rgs_django_utils.database.dj_extended_models.ArrayField(base_field=rgs_django_utils.database.dj_extended_models.TextField(), blank=True, null=True, size=None)),
                ('data', rgs_django_utils.database.dj_extended_models.JSONField(blank=True, null=True, verbose_name='data')),
                ('msg_code', rgs_django_utils.database.dj_extended_models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rgs_django_utils.enummessagecode', verbose_name='meldingscode')),
                ('obj_type', rgs_django_utils.database.dj_extended_models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rgs_django_utils.enumsourcetype')),
                ('workflow', rgs_django_utils.database.dj_extended_models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='datalogs', to='rgs_django_utils.workflow')),
            ],
            options={
                'verbose_name': 'workflow data log',
                'verbose_name_plural': 'workflow data logs',
                'db_table': 'workflow_data_log',
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', rgs_django_utils.database.dj_extended_models.TextField(primary_key=True, serialize=False, verbose_name='identification')),
                ('name', rgs_django_utils.database.dj_extended_models.TextField(verbose_name='naam')),
                ('description', rgs_django_utils.database.dj_extended_models.TextField(blank=True, null=True, verbose_name='omschrijving')),
                ('access_by', rgs_django_utils.database.dj_extended_models.ArrayField(base_field=rgs_django_utils.database.dj_extended_models.TextField(), db_default="{'developer'}", size=None, verbose_name='toegankelijk voor')),
                ('modules', rgs_django_utils.database.dj_extended_models.ArrayField(base_field=rgs_django_utils.database.dj_extended_models.TextField(), db_default='{}', size=None, verbose_name='modules')),
                ('for_data_types', rgs_django_utils.database.dj_extended_models.ArrayField(base_field=rgs_django_utils.database.dj_extended_models.TextField(), db_default="{'project'}", size=None, verbose_name='modules')),
                ('steps', rgs_django_utils.database.dj_extended_models.ArrayField(base_field=rgs_django_utils.database.dj_extended_models.TextField(), db_default='{}', size=None, verbose_name='stappen')),
                ('source_type', rgs_django_utils.database.dj_extended_models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rgs_django_utils.enumsourcetype', verbose_name='bron type')),
                ('workflow_type', rgs_django_utils.database.dj_extended_models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rgs_django_utils.enumworkflowtype', verbose_name='type')),
            ],
            options={
                'verbose_name': 'workflow template',
                'verbose_name_plural': 'workflow templates',
                'db_table': 'workflow_template',
            },
        ),
        migrations.AddField(
            model_name='workflow',
            name='template',
            field=rgs_django_utils.database.dj_extended_models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rgs_django_utils.workflowtemplate'),
        ),
        migrations.CreateModel(
            name='DescriptionFieldInputForCalc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calc', rgs_django_utils.database.dj_extended_models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_fields', to='rgs_django_utils.descriptioncalculation', verbose_name='berekening')),
                ('field', rgs_django_utils.database.dj_extended_models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_for_calc', to='rgs_django_utils.descriptionfield', verbose_name='veld')),
            ],
            options={
                'verbose_name': 'veld input voor berekening',
                'verbose_name_plural': 'veld input voor berekeningen',
                'db_table': 'descr_field_input_for_calc',
                'constraints': [models.UniqueConstraint(fields=('calc', 'field'), name='unique_descr_field_input_for_calc')],
            },
        ),
        migrations.AddConstraint(
            model_name='descriptionfieldsection',
            constraint=models.UniqueConstraint(fields=('table', 'code'), name='unique_section'),
        ),
        migrations.AddConstraint(
            model_name='descriptionfield',
            constraint=models.UniqueConstraint(fields=('table', 'column_name'), name='unique_descr_field'),
        ),
    ]
