# Generated by Django 5.2.1 on 2025-06-21 14:54

import django.db.models.deletion
import rgs_django_utils.database.dj_extended_models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionCalculation',
            fields=[
                ('id', rgs_django_utils.database.dj_extended_models.IntegerField(primary_key=True, serialize=False)),
                ('name', rgs_django_utils.database.dj_extended_models.TextField()),
                ('description', rgs_django_utils.database.dj_extended_models.TextField(verbose_name='description')),
            ],
            options={
                'verbose_name': 'berekening',
                'verbose_name_plural': 'berekeningen',
                'db_table': 'descr_calculation',
            },
        ),
        migrations.CreateModel(
            name='DescriptionEnumTableType',
            fields=[
                ('id', rgs_django_utils.database.dj_extended_models.TextStringField(primary_key=True, serialize=False, verbose_name='code')),
                ('name', rgs_django_utils.database.dj_extended_models.TextStringField(verbose_name='name')),
            ],
            options={
                'verbose_name': 'tabeltype',
                'verbose_name_plural': 'tabeltypes',
                'db_table': 'descr_enum_table_type',
            },
        ),
        migrations.CreateModel(
            name='DescriptionTableSection',
            fields=[
                ('code', rgs_django_utils.database.dj_extended_models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', rgs_django_utils.database.dj_extended_models.TextField(blank=True, null=True, verbose_name='naam')),
                ('order', rgs_django_utils.database.dj_extended_models.IntegerField(db_default=-1, verbose_name='volgorde')),
                ('description', rgs_django_utils.database.dj_extended_models.TextField(blank=True, null=True, verbose_name='omschrijving')),
            ],
            options={
                'verbose_name': 'sectie',
                'verbose_name_plural': 'secties',
                'db_table': 'descr_table_section',
            },
        ),
        migrations.CreateModel(
            name='EnumAuthMethod',
            fields=[
                ('id', rgs_django_utils.database.dj_extended_models.TextStringField(primary_key=True, serialize=False, verbose_name='code')),
                ('name', rgs_django_utils.database.dj_extended_models.TextStringField(verbose_name='name')),
            ],
            options={
                'verbose_name': 'authenticatie methode',
                'verbose_name_plural': 'authenticatie methoden',
                'db_table': 'enum_auth_method',
            },
        ),
        migrations.CreateModel(
            name='EnumModule',
            fields=[
                ('id', rgs_django_utils.database.dj_extended_models.TextStringField(primary_key=True, serialize=False, verbose_name='code')),
                ('name', rgs_django_utils.database.dj_extended_models.TextStringField(verbose_name='name')),
            ],
            options={
                'verbose_name': 'module',
                'verbose_name_plural': 'modules',
                'db_table': 'enum_module',
            },
        ),
        migrations.CreateModel(
            name='EnumRole',
            fields=[
                ('id', rgs_django_utils.database.dj_extended_models.TextStringField(primary_key=True, serialize=False, verbose_name='code')),
                ('name', rgs_django_utils.database.dj_extended_models.TextStringField(verbose_name='name')),
            ],
            options={
                'verbose_name': 'Gebruikersrol',
                'verbose_name_plural': 'Gebruikersrollen',
                'db_table': 'enum_role',
            },
        ),
        migrations.CreateModel(
            name='DescriptionTable',
            fields=[
                ('id', rgs_django_utils.database.dj_extended_models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='database tabel')),
                ('order', rgs_django_utils.database.dj_extended_models.IntegerField(db_default=-1)),
                ('model', rgs_django_utils.database.dj_extended_models.TextField(blank=True, null=True, verbose_name='model')),
                ('name', rgs_django_utils.database.dj_extended_models.TextField(verbose_name='naam')),
                ('name_plural', rgs_django_utils.database.dj_extended_models.TextField(blank=True, null=True, verbose_name='naam meervoud')),
                ('description', rgs_django_utils.database.dj_extended_models.TextField(blank=True, null=True, verbose_name='description')),
                ('modules', rgs_django_utils.database.dj_extended_models.TextField(default='*')),
                ('with_history', rgs_django_utils.database.dj_extended_models.BooleanField(db_default=False, verbose_name='met historie')),
                ('table_type', rgs_django_utils.database.dj_extended_models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rgs_django_utils.descriptionenumtabletype', verbose_name='tabeltype')),
                ('section', rgs_django_utils.database.dj_extended_models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='rgs_django_utils.descriptiontablesection', verbose_name='sectie')),
            ],
            options={
                'verbose_name': 'tabelbeschrijving',
                'verbose_name_plural': 'tabelbeschrijvingen',
                'db_table': 'descr_table',
            },
        ),
        migrations.CreateModel(
            name='DescriptionFieldSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', rgs_django_utils.database.dj_extended_models.CharField(max_length=50)),
                ('name', rgs_django_utils.database.dj_extended_models.TextField(blank=True, null=True, verbose_name='naam')),
                ('order', rgs_django_utils.database.dj_extended_models.IntegerField(db_default=-1, verbose_name='volgorde')),
                ('description', rgs_django_utils.database.dj_extended_models.TextField(blank=True, null=True, verbose_name='omschrijving')),
                ('table', rgs_django_utils.database.dj_extended_models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_sections', to='rgs_django_utils.descriptiontable', verbose_name='tabel')),
            ],
            options={
                'verbose_name': 'veldsectie',
                'verbose_name_plural': 'veldsecties',
                'db_table': 'descr_field_section',
            },
        ),
        migrations.CreateModel(
            name='DescriptionField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', rgs_django_utils.database.dj_extended_models.IntegerField(db_default=-1, verbose_name='volgorde')),
                ('column_name', rgs_django_utils.database.dj_extended_models.TextField(verbose_name='kolomnaam')),
                ('verbose_name', rgs_django_utils.database.dj_extended_models.TextField(verbose_name='naam')),
                ('dbf_name', rgs_django_utils.database.dj_extended_models.CharField(blank=True, max_length=10, null=True, verbose_name='dbf naam')),
                ('field_type', rgs_django_utils.database.dj_extended_models.TextField(verbose_name='veldtype')),
                ('max_length', rgs_django_utils.database.dj_extended_models.IntegerField(blank=True, null=True, verbose_name='maximale lengte')),
                ('nullable', rgs_django_utils.database.dj_extended_models.BooleanField(verbose_name='nullable')),
                ('precision', rgs_django_utils.database.dj_extended_models.IntegerField(blank=True, null=True, verbose_name='aantal decimalen')),
                ('is_relation', rgs_django_utils.database.dj_extended_models.BooleanField(db_default=False, verbose_name='is relatie')),
                ('modules', rgs_django_utils.database.dj_extended_models.TextField(default='*')),
                ('doc_unit', rgs_django_utils.database.dj_extended_models.TextField(blank=True, null=True, verbose_name='eenheid')),
                ('doc_short', rgs_django_utils.database.dj_extended_models.TextField(blank=True, null=True, verbose_name='omschrijving kort')),
                ('doc_full', rgs_django_utils.database.dj_extended_models.TextField(blank=True, null=True, verbose_name='omschrijving volledig')),
                ('doc_constraint', rgs_django_utils.database.dj_extended_models.TextField(blank=True, null=True, verbose_name='omschrijving voorwaarde')),
                ('doc_development', rgs_django_utils.database.dj_extended_models.TextField(blank=True, null=True, verbose_name='omschrijving voor ontwikkelaars')),
                ('import_mode', rgs_django_utils.database.dj_extended_models.TextStringField(default='all', verbose_name='import mode')),
                ('export', rgs_django_utils.database.dj_extended_models.BooleanField(db_default=True, verbose_name='export')),
                ('default_value', rgs_django_utils.database.dj_extended_models.TextField(blank=True, null=True, verbose_name='default waarde of functie')),
                ('with_history', rgs_django_utils.database.dj_extended_models.BooleanField(db_default=False, verbose_name='gebruikt in historie trigger')),
                ('calc_by', rgs_django_utils.database.dj_extended_models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='rgs_django_utils.descriptioncalculation', verbose_name='berekening')),
                ('field_section', rgs_django_utils.database.dj_extended_models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='rgs_django_utils.descriptionfieldsection', verbose_name='veldsectie')),
                ('relation_table', rgs_django_utils.database.dj_extended_models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relation_fields', to='rgs_django_utils.descriptiontable', verbose_name='relatie tabel')),
                ('table', rgs_django_utils.database.dj_extended_models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='rgs_django_utils.descriptiontable', verbose_name='tabel')),
            ],
            options={
                'verbose_name': 'veld',
                'verbose_name_plural': 'velden',
                'db_table': 'descr_field',
            },
        ),
        migrations.AddField(
            model_name='descriptioncalculation',
            name='table',
            field=rgs_django_utils.database.dj_extended_models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='rgs_django_utils.descriptiontable', verbose_name='tabel'),
        ),
        migrations.CreateModel(
            name='EnumAuthMethodExtended',
            fields=[
                ('name', rgs_django_utils.database.dj_extended_models.TextStringField(verbose_name='name')),
                ('order', rgs_django_utils.database.dj_extended_models.IntegerField(verbose_name='volgorde')),
                ('available', rgs_django_utils.database.dj_extended_models.BooleanField(default=False, verbose_name='beschikbaar')),
                ('extra_costs', rgs_django_utils.database.dj_extended_models.BooleanField(verbose_name='extra kosten')),
                ('am_note', rgs_django_utils.database.dj_extended_models.TextField(blank=True, null=True, verbose_name='notities applicatie/ontwikkelaars')),
                ('id', rgs_django_utils.database.dj_extended_models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extended', serialize=False, to='rgs_django_utils.enumauthmethod')),
            ],
            options={
                'verbose_name': 'authenticatie methode',
                'verbose_name_plural': 'authenticatie methoden',
                'db_table': 'enum_auth_method_ext',
            },
        ),
        migrations.CreateModel(
            name='EnumModuleExtended',
            fields=[
                ('name', rgs_django_utils.database.dj_extended_models.TextStringField(verbose_name='name')),
                ('order', rgs_django_utils.database.dj_extended_models.IntegerField()),
                ('available', rgs_django_utils.database.dj_extended_models.BooleanField(default=True)),
                ('id', rgs_django_utils.database.dj_extended_models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extended', serialize=False, to='rgs_django_utils.enummodule')),
            ],
            options={
                'verbose_name': 'module',
                'verbose_name_plural': 'modules',
                'db_table': 'enum_module_ext',
            },
        ),
        migrations.CreateModel(
            name='EnumRoleExtended',
            fields=[
                ('name', rgs_django_utils.database.dj_extended_models.TextStringField(verbose_name='name')),
                ('for_staff', rgs_django_utils.database.dj_extended_models.BooleanField(default=False, verbose_name='Voor superuser')),
                ('for_org', rgs_django_utils.database.dj_extended_models.BooleanField(default=False, verbose_name='Voor organisatie')),
                ('for_project', rgs_django_utils.database.dj_extended_models.BooleanField(default=False, verbose_name='Voor project')),
                ('order', rgs_django_utils.database.dj_extended_models.IntegerField(default=0, verbose_name='volgorde')),
                ('description', rgs_django_utils.database.dj_extended_models.TextField(verbose_name='omschrijving')),
                ('id', rgs_django_utils.database.dj_extended_models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extended', serialize=False, to='rgs_django_utils.enumrole')),
            ],
            options={
                'verbose_name': 'Gebruikersrol',
                'verbose_name_plural': 'Gebruikersrollen',
                'db_table': 'enum_role_ext',
            },
        ),
        migrations.CreateModel(
            name='DescriptionFieldInputForCalc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calc', rgs_django_utils.database.dj_extended_models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_fields', to='rgs_django_utils.descriptioncalculation', verbose_name='berekening')),
                ('field', rgs_django_utils.database.dj_extended_models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_for_calc', to='rgs_django_utils.descriptionfield', verbose_name='veld')),
            ],
            options={
                'verbose_name': 'veld input voor berekening',
                'verbose_name_plural': 'veld input voor berekeningen',
                'db_table': 'descr_field_input_for_calc',
                'constraints': [models.UniqueConstraint(fields=('calc', 'field'), name='unique_descr_field_input_for_calc')],
            },
        ),
        migrations.AddConstraint(
            model_name='descriptionfieldsection',
            constraint=models.UniqueConstraint(fields=('table', 'code'), name='unique_section'),
        ),
        migrations.AddConstraint(
            model_name='descriptionfield',
            constraint=models.UniqueConstraint(fields=('table', 'column_name'), name='unique_descr_field'),
        ),
    ]
