# Generated by Django 5.2.3 on 2025-06-27 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rgs_django_utils', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enummoduleextended',
            name='id',
        ),
        migrations.DeleteModel(
            name='EnumModule',
        ),
        migrations.DeleteModel(
            name='EnumModuleExtended',
        ),
    ]
