# Generated by Django 5.2.5 on 2025-09-19 14:07

import rgs_django_utils.database.dj_extended_models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rgs_django_utils', '0002_remove_enummoduleextended_id_delete_enummodule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnumAccessThrough',
            fields=[
                ('id', rgs_django_utils.database.dj_extended_models.TextStringField(primary_key=True, serialize=False, verbose_name='code')),
                ('name', rgs_django_utils.database.dj_extended_models.TextStringField(verbose_name='name')),
            ],
            options={
                'verbose_name': 'toegang via',
                'verbose_name_plural': 'toegang via',
                'db_table': 'enum_access_through',
            },
        ),
    ]
