# Generated by Django 5.0.6 on 2024-07-12 13:56

import django.db.models.deletion
import rgs_utils.database.dj_extended_models
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rgs_utils', '0003_alter_projectfile_created_by_alter_task_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='created_by',
            field=rgs_utils.database.dj_extended_models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='aangemaakt door'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='last_modified_by',
            field=rgs_utils.database.dj_extended_models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='last_modified_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='laatst aangepast door'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=rgs_utils.database.dj_extended_models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='aangemaakt door'),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_modified_by',
            field=rgs_utils.database.dj_extended_models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='last_modified_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='laatst aangepast door'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='created_by',
            field=rgs_utils.database.dj_extended_models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='aangemaakt door'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='last_modified_by',
            field=rgs_utils.database.dj_extended_models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='last_modified_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='laatst aangepast door'),
        ),
    ]
