# Generated by Django 5.0.6 on 2024-07-12 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rgs_utils', '0004_alter_projectfile_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflowtemplate',
            old_name='ids',
            new_name='id',
        ),
    ]
