# Generated by Django 5.0.6 on 2024-08-07 15:12

import django.db.models.deletion
import rgs_utils.database.dj_extended_models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rgs_utils', '0005_rename_ids_workflowtemplate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enumauthmethodextended',
            name='id',
            field=rgs_utils.database.dj_extended_models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extended', serialize=False, to='rgs_utils.enumauthmethod'),
        ),
        migrations.AlterField(
            model_name='enumdatatypeextended',
            name='id',
            field=rgs_utils.database.dj_extended_models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extended', serialize=False, to='rgs_utils.enumdatatype'),
        ),
        migrations.AlterField(
            model_name='enummessagecodeextended',
            name='id',
            field=rgs_utils.database.dj_extended_models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extended', serialize=False, to='rgs_utils.enummessagecode'),
        ),
        migrations.AlterField(
            model_name='enumroleextended',
            name='id',
            field=rgs_utils.database.dj_extended_models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extended', serialize=False, to='rgs_utils.enumrole'),
        ),
        migrations.AlterField(
            model_name='enumsourcetypeextended',
            name='id',
            field=rgs_utils.database.dj_extended_models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extended', serialize=False, to='rgs_utils.enumsourcetype'),
        ),
        migrations.AlterField(
            model_name='enumtaskstatusextended',
            name='id',
            field=rgs_utils.database.dj_extended_models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extended', serialize=False, to='rgs_utils.enumtaskstatus'),
        ),
        migrations.AlterField(
            model_name='enumworkflowstepextended',
            name='id',
            field=rgs_utils.database.dj_extended_models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extended', serialize=False, to='rgs_utils.enumworkflowstep'),
        ),
    ]
