# Generated by Django 5.0.6 on 2024-08-09 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rgs_utils', '0013_alter_taskprogress_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskprogress',
            old_name='id',
            new_name='task',
        ),
    ]
