# Generated by Django 5.0.6 on 2024-08-09 09:28

import rgs_utils.database.dj_extended_models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rgs_utils', '0014_rename_id_taskprogress_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='input',
        ),
        migrations.AddField(
            model_name='task',
            name='output',
            field=rgs_utils.database.dj_extended_models.JSONField(blank=True, null=True, verbose_name='output'),
        ),
    ]
