# Generated by Django 5.0.6 on 2024-08-09 09:47

import django.db.models.deletion
import rgs_utils.database.dj_extended_models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rgs_utils', '0015_remove_task_input_task_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='active_step',
            field=rgs_utils.database.dj_extended_models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rgs_utils.task', verbose_name='actieve stap'),
        ),
    ]
