# Generated by Django 5.0.6 on 2024-07-12 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rgs_utils', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflow',
            old_name='workflow',
            new_name='template',
        ),
    ]
