# Generated by Django 5.0.6 on 2024-08-08 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rgs_utils', '0007_alter_enumauthmethodextended_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enumworkflowstep',
            options={'verbose_name': 'Workflow stap', 'verbose_name_plural': 'workflow stappen'},
        ),
        migrations.AlterModelOptions(
            name='enumworkflowstepextended',
            options={'verbose_name': 'Workflow stap', 'verbose_name_plural': 'workflow stappen'},
        ),
        migrations.AlterModelTable(
            name='enumworkflowstep',
            table='enum_workflow_step',
        ),
        migrations.AlterModelTable(
            name='enumworkflowstepextended',
            table='enum_workflow_step_ext',
        ),
    ]
