# Generated by Django 5.0.6 on 2024-08-08 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rgs_utils', '0008_alter_enumworkflowstep_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enumworkflowtype',
            options={'verbose_name': 'workflow type', 'verbose_name_plural': 'workflow types'},
        ),
        migrations.AlterModelTable(
            name='enumworkflowtype',
            table='enum_workflow_type',
        ),
    ]
