# Generated by Django 5.0.6 on 2024-08-08 09:56

import django.db.models.deletion
import rgs_utils.database.dj_extended_models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rgs_utils', '0009_alter_enumworkflowtype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='step',
            field=rgs_utils.database.dj_extended_models.ForeignKey(default='default', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rgs_utils.enumworkflowstep', verbose_name='stap'),
            preserve_default=False,
        ),
    ]
