# Generated by Django 5.0.6 on 2024-08-08 13:03

import rgs_utils.database.dj_extended_models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rgs_utils', '0010_alter_task_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='enumworkflowstepextended',
            name='action',
            field=rgs_utils.database.dj_extended_models.TextField(default='', verbose_name='actie'),
        ),
    ]
