# Generated by Django 5.0.6 on 2024-08-09 07:30

import django.db.models.deletion
import rgs_utils.database.dj_extended_models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rgs_utils', '0011_enumworkflowstepextended_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskprogress',
            name='task',
        ),
        migrations.AlterField(
            model_name='taskprogress',
            name='id',
            field=rgs_utils.database.dj_extended_models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='progress', serialize=False, to='rgs_utils.task'),
        ),
    ]
