# Generated by Django 5.0.6 on 2024-08-20 07:54

import rgs_utils.database.dj_extended_models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rgs_utils', '0016_workflow_active_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='locked',
            field=rgs_utils.database.dj_extended_models.BooleanField(default=False),
        ),
    ]
