# Generated by Django 5.0.6 on 2024-09-11 12:12

import rgs_utils.database.dj_extended_models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rgs_utils', '0017_task_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='locked',
        ),
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='config',
        ),
        migrations.AddField(
            model_name='workflow',
            name='locked',
            field=rgs_utils.database.dj_extended_models.BooleanField(default=False),
        ),
    ]
