# Generated by Django 5.0.9 on 2025-02-10 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rgs_utils', '0018_remove_task_locked_remove_task_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enumauthmethodextended',
            name='combine_with_2FA',
        ),
    ]
