# Generated by Django 3.1.4 on 2021-10-13 09:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('ids', models.TextField()),
                ('int_field', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'verbose_parent_model',
            },
        ),
        migrations.CreateModel(
            name='MiddleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('ids', models.TextField()),
                ('parent_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.parentmodel', verbose_name='verbose_parent_model')),
            ],
            options={
                'verbose_name': 'verbose_middle_model',
            },
        ),
        migrations.CreateModel(
            name='ManyToManyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('ids', models.TextField()),
                ('middle_model_m2m', models.ManyToManyField(to='testapp.MiddleModel')),
            ],
            options={
                'verbose_name': 'verbose_middle_model',
            },
        ),
        migrations.CreateModel(
            name='ChildModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('ids', models.TextField()),
                ('middle_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.middlemodel')),
            ],
            options={
                'verbose_name': 'verbose_middle_model',
            },
        ),
    ]
